### ISSUE TITLE
Configure `redstone-smartweave` package to support webpack v5

### ISSUE THREAD

**Issue by DanMacDonald** [redstone-finance/redstone-smartcontracts#105]
Current version of the `redstone-smartweave` package does not play well with webpack v5+.

Using the latest `create-react-app`, generate a new sample project.
```
npm i arweave
npm i redstone-smartweave
```
add the following code...
```js
const redstone = SmartWeaveWebFactory.memCached(arweave);
const ctr = redstone.contract("t9T7DIOGxx4VWXoCEeYYarFYeERTpWIC1V3y-BPZgKE");
LoggerFactory.INST.logLevel("error");
ctr.readState().then(r => console.log(r));
```
Observe as node dependency errors ensue...
![image](https://user-images.githubusercontent.com/3269261/155394133-003c2735-330f-44ed-8b0f-7dc89d4c1aa6.png)

Apparently there is a way to structure the package.json in the package to better support targeting the browser platform by default.

https://github.com/webpack/webpack/issues/4674

^ provided here for context.

# Expected Result:
Including `redstone-smartweave` should not introduce compile errors when included in a browser/web project.

**Comment by ppedziwiatr** [comment]
@DanMacDonald , thanks for the detailed description, we will try to fix this asap.
@asiaziola , as we've discussed - let's try with `redstone-isomorphic`

**Comment by asiaziola** [comment]
@DanMacDonald v0.4.40 with the fix for the webpack 5 support has been released. Feel free to test it out. I prepared a sample app with the new version plugged in https://github.com/redstone-finance/redstone-smartcontracts-webpack5-app. There's been one problem which affects not only our sdk but also e.g. arweave-js sdk. You will see some warnings about webpack not being able to parse sdks' source maps. Again, seems to be a problem only for v5. These are just warnings and and not errors but I still consider them as an issue. You should also see them when not using our sdk but only arweave-js? Anyway, you can read some more about it here: https://github.com/facebook/create-react-app/pull/8227 (basically it's needed for a better debugging in case of ts libraries). As a small workaround I added in my app following flag: `"start": "GENERATE_SOURCEMAP=false react-scripts start"` which omits generating source maps. However, I would love to hear your opinion if you will have some time to test it out.

**Comment by DanMacDonald** [comment]
Yes, I've seen this source maps issues with many packages on V5. It seems to be a harmless warning however. Will check it out soon!
