### ISSUE TITLE
feat: add flag to disallow state evaluation when using unsafeClient

### ISSUE THREAD

**Issue by balthazar** [redstone-finance/redstone-smartcontracts#136]
The SDK should allow passing of a flag to prevent state evaluation of non-deterministic contracts using the unsafeClient.

I think throwing an error when this flag is set would be the good way to do things, but open to other thoughts.

**Comment by ppedziwiatr** [comment]
introduced in `v0.4.82`.
using unsafeClient is now blocked by default.

In order to evaluate the state of the contracts that are using the unsafeClient - set `EvaluationOptions.allowUnsafeClient` to true. 
Why unsafeClient is evil - https://discord.com/channels/357957786904166400/756557551234973696/969141443987902464
